{% set name = "album-package" %}
{% set version = "0.5.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/album_package-{{ version }}.tar.gz
  sha256: 697023838b434486edc33605cecdc30d1de9ae6742b7f31b6ce1903fc0c196d7

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
    - wheel
  run:
    - python >={{ python_min }}
    - {{ pin_compatible('album', lower_bound='0.11.0', upper_bound='0.13.0') }}
    - {{ pin_compatible('album-gui', lower_bound='0.5.0', upper_bound='0.6.0') }}
    - pyinstaller >={{ 4.8 }}

test:
  imports:
    - album
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://gitlab.com/album-app/plugins/album-package
  summary: album plugin for packaging a solution
  dev_url: https://gitlab.com/album-app/plugins/album-package
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - jpalbrecht
